// Mocks generated by Mockito 5.4.6 from annotations
// in pusher_reverb_flutter/test/facades/reverb_remote_events_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:async/async.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pusher_reverb_flutter/pusher_reverb_flutter.dart' as _i7;
import 'package:pusher_reverb_flutter/src/authentications/channel_authenticator.dart'
    as _i4;
import 'package:pusher_reverb_flutter/src/models/channel_event.dart' as _i9;
import 'package:stream_channel/stream_channel.dart' as _i3;
import 'package:web_socket_channel/src/channel.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWebSocketSink_0 extends _i1.SmartFake implements _i2.WebSocketSink {
  _FakeWebSocketSink_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamChannel_1<T> extends _i1.SmartFake
    implements _i3.StreamChannel<T> {
  _FakeStreamChannel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannelAuthenticator_2 extends _i1.SmartFake
    implements _i4.ChannelAuthenticator {
  _FakeChannelAuthenticator_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WebSocketChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketChannel extends _i1.Mock implements _i2.WebSocketChannel {
  @override
  _i5.Future<void> get ready =>
      (super.noSuchMethod(
            Invocation.getter(#ready),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<dynamic> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i5.Stream<dynamic>.empty(),
          )
          as _i5.Stream<dynamic>);

  @override
  _i2.WebSocketSink get sink =>
      (super.noSuchMethod(
            Invocation.getter(#sink),
            returnValue: _FakeWebSocketSink_0(this, Invocation.getter(#sink)),
            returnValueForMissingStub: _FakeWebSocketSink_0(
              this,
              Invocation.getter(#sink),
            ),
          )
          as _i2.WebSocketSink);

  @override
  void pipe(_i3.StreamChannel<dynamic>? other) => super.noSuchMethod(
    Invocation.method(#pipe, [other]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.StreamChannel<S> transform<S>(
    _i3.StreamChannelTransformer<S, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [transformer]),
            returnValue: _FakeStreamChannel_1<S>(
              this,
              Invocation.method(#transform, [transformer]),
            ),
            returnValueForMissingStub: _FakeStreamChannel_1<S>(
              this,
              Invocation.method(#transform, [transformer]),
            ),
          )
          as _i3.StreamChannel<S>);

  @override
  _i3.StreamChannel<dynamic> transformStream(
    _i5.StreamTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformStream, [transformer]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#transformStream, [transformer]),
            ),
            returnValueForMissingStub: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#transformStream, [transformer]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> transformSink(
    _i6.StreamSinkTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformSink, [transformer]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#transformSink, [transformer]),
            ),
            returnValueForMissingStub: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#transformSink, [transformer]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> changeStream(
    _i5.Stream<dynamic> Function(_i5.Stream<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeStream, [change]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#changeStream, [change]),
            ),
            returnValueForMissingStub: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#changeStream, [change]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> changeSink(
    _i5.StreamSink<dynamic> Function(_i5.StreamSink<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeSink, [change]),
            returnValue: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#changeSink, [change]),
            ),
            returnValueForMissingStub: _FakeStreamChannel_1<dynamic>(
              this,
              Invocation.method(#changeSink, [change]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<S> cast<S>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _FakeStreamChannel_1<S>(
              this,
              Invocation.method(#cast, []),
            ),
            returnValueForMissingStub: _FakeStreamChannel_1<S>(
              this,
              Invocation.method(#cast, []),
            ),
          )
          as _i3.StreamChannel<S>);
}

/// A class which mocks [WebSocketSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketSink extends _i1.Mock implements _i2.WebSocketSink {
  @override
  _i5.Future<dynamic> get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> close([int? closeCode, String? closeReason]) =>
      (super.noSuchMethod(
            Invocation.method(#close, [closeCode, closeReason]),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  void add(dynamic data) => super.noSuchMethod(
    Invocation.method(#add, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<dynamic> addStream(_i5.Stream<dynamic>? stream) =>
      (super.noSuchMethod(
            Invocation.method(#addStream, [stream]),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}

/// A class which mocks [ReverbChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockReverbChannel extends _i1.Mock implements _i7.ReverbChannel {
  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i7.ChannelState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.ChannelState.unsubscribed,
            returnValueForMissingStub: _i7.ChannelState.unsubscribed,
          )
          as _i7.ChannelState);

  @override
  _i5.Stream<_i9.ChannelEvent> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i9.ChannelEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i9.ChannelEvent>.empty(),
          )
          as _i5.Stream<_i9.ChannelEvent>);

  @override
  _i5.Future<void> subscribe({required String? socketId}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {#socketId: socketId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribe() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i9.ChannelEvent> on(String? eventName) =>
      (super.noSuchMethod(
            Invocation.method(#on, [eventName]),
            returnValue: _i5.Stream<_i9.ChannelEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i9.ChannelEvent>.empty(),
          )
          as _i5.Stream<_i9.ChannelEvent>);

  @override
  void bind(String? eventName, _i7.ChannelEventListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#bind, [eventName, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void unbind(String? eventName, [_i7.ChannelEventListener? listener]) =>
      super.noSuchMethod(
        Invocation.method(#unbind, [eventName, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void addStateListener(_i7.ChannelStateListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#addStateListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeStateListener(_i7.ChannelStateListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeStateListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void handleEvent(String? eventName, dynamic data) => super.noSuchMethod(
    Invocation.method(#handleEvent, [eventName, data]),
    returnValueForMissingStub: null,
  );

  @override
  void handleSubscriptionSucceeded() => super.noSuchMethod(
    Invocation.method(#handleSubscriptionSucceeded, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleUnsubscriptionSucceeded() => super.noSuchMethod(
    Invocation.method(#handleUnsubscriptionSucceeded, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void sendMessage(String? message) => super.noSuchMethod(
    Invocation.method(#sendMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void setState(_i7.ChannelState? newState) => super.noSuchMethod(
    Invocation.method(#setState, [newState]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ReverbPresenceChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockReverbPresenceChannel extends _i1.Mock
    implements _i7.ReverbPresenceChannel {
  @override
  List<_i7.PresenceMember> get members =>
      (super.noSuchMethod(
            Invocation.getter(#members),
            returnValue: <_i7.PresenceMember>[],
            returnValueForMissingStub: <_i7.PresenceMember>[],
          )
          as List<_i7.PresenceMember>);

  @override
  int get memberCount =>
      (super.noSuchMethod(
            Invocation.getter(#memberCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Authorizer get authorizer =>
      (super.noSuchMethod(
            Invocation.getter(#authorizer),
            returnValue: (String channelName, String socketId) =>
                _i5.Future<Map<String, String>>.value(<String, String>{}),
            returnValueForMissingStub: (String channelName, String socketId) =>
                _i5.Future<Map<String, String>>.value(<String, String>{}),
          )
          as _i7.Authorizer);

  @override
  String get authEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#authEndpoint),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#authEndpoint),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#authEndpoint),
            ),
          )
          as String);

  @override
  _i4.ChannelAuthenticator get channelAuthenticator =>
      (super.noSuchMethod(
            Invocation.getter(#channelAuthenticator),
            returnValue: _FakeChannelAuthenticator_2(
              this,
              Invocation.getter(#channelAuthenticator),
            ),
            returnValueForMissingStub: _FakeChannelAuthenticator_2(
              this,
              Invocation.getter(#channelAuthenticator),
            ),
          )
          as _i4.ChannelAuthenticator);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i7.ChannelState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.ChannelState.unsubscribed,
            returnValueForMissingStub: _i7.ChannelState.unsubscribed,
          )
          as _i7.ChannelState);

  @override
  _i5.Stream<_i9.ChannelEvent> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i9.ChannelEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i9.ChannelEvent>.empty(),
          )
          as _i5.Stream<_i9.ChannelEvent>);

  @override
  _i5.Future<void> subscribe({required String? socketId}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {#socketId: socketId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void handleSubscriptionSucceeded([dynamic data]) => super.noSuchMethod(
    Invocation.method(#handleSubscriptionSucceeded, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void handleEvent(String? eventName, dynamic data) => super.noSuchMethod(
    Invocation.method(#handleEvent, [eventName, data]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> unsubscribe() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i9.ChannelEvent> on(String? eventName) =>
      (super.noSuchMethod(
            Invocation.method(#on, [eventName]),
            returnValue: _i5.Stream<_i9.ChannelEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i9.ChannelEvent>.empty(),
          )
          as _i5.Stream<_i9.ChannelEvent>);

  @override
  void bind(String? eventName, _i7.ChannelEventListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#bind, [eventName, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void unbind(String? eventName, [_i7.ChannelEventListener? listener]) =>
      super.noSuchMethod(
        Invocation.method(#unbind, [eventName, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void addStateListener(_i7.ChannelStateListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#addStateListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeStateListener(_i7.ChannelStateListener? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeStateListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void handleUnsubscriptionSucceeded() => super.noSuchMethod(
    Invocation.method(#handleUnsubscriptionSucceeded, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void sendMessage(String? message) => super.noSuchMethod(
    Invocation.method(#sendMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void setState(_i7.ChannelState? newState) => super.noSuchMethod(
    Invocation.method(#setState, [newState]),
    returnValueForMissingStub: null,
  );
}
